export const allData = [
  {
    categoryImage: "/category/cat10.png",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat02.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat03.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat04.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat05.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat06.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat07.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat08.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
  {
    categoryImage: "/category/cat09.png     ",
    beauty: "Beauty",
    instant: "Instant",
    time: "1h 30mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      " a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: " Portfolio",
    nearly: " Nearly There",
    places: "4 Places left",
    status: " Online",
    discountPrice: "47.60",
    price: "60.00",
    name: " Rebecca",
    address: " Salon, CV37 ",
    address2: " Stratford-upon-Avon",
    rating: "5",
    count: "15",
    userImage: "/category/user.png",
  },
];
