const myFavouriteData = [
  {
    beauty: "beauty",
    instant: "instant",
    categoryImage: "favourite/fav01.jpg",
    heading: "Beauty",
    time: "30  mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      "a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: "Portfolio",
    nearly: "Nearly There",
    places: "4 Places left",
    discountPrice: "47.60",
    status: "No Availability",
    price: " 60.00",
    name: "Rebecca",
    address: "Salon, CV37",
    address2: "Stratford-upon-Avon",
    rating: "5",
    count: "15",
  },
  {
    beauty: "beauty",
    instant: "instant",
    categoryImage: "favourite/fav02.jpg",
    heading: "Beauty",
    time: "1h 30  mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      "a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: "Portfolio",
    nearly: "Nearly There",
    places: "4 Places left",
    discountPrice: "47.60",
    status: "See Availability",
    price: " 60.00 ",
    name: "Rebecca",
    address: "Salon, CV37",
    address2: "Stratford-upon-Avon",
    rating: "5",
    count: "15",
  },
  {
    beauty: "beauty",
    categoryImage: "favourite/fav03.jpg",
    heading: "Beauty",
    time: "1h 30  mins",
    detail: "Nutritional evaluation for full overall...",
    description:
      "a full in depth and detailed consultation of your nutrition and lifestyle for optimal health",
    portfolio: "Portfolio",
    nearly: "Nearly There",
    places: "4 Places left",
    discountPrice: "47.60",
    status: "See Availability",
    price: " 60.00",
    name: "Rebecca",
    address: "Salon, CV37",
    address2: "Stratford-upon-Avon",
    rating: "5",
    count: "15",
  },
];

export default myFavouriteData;
